name: Python 3.x application with uv on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.13", "3.14" ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install uv - latest if not defined in `pyproject.toml`
      uses: astral-sh/setup-uv@v6

    - name: Setup Python ${{ matrix.python-version }}
      # Faster than using uv, as it caches Python on GitHub runner
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install project using existing lockfile
      run: uv sync --locked

    - name: Lint with ruff
      # by default: exit with error if rule violations
      run: uv run ruff check --output-format=github

    - name: Lint format with ruff
      # by default: exit with error if rule violations
      run: uv run ruff format
